// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaK2FhTT3LmC2Ljt2UIsYukGadSrNs0pc',
    appId: '1:630177566427:android:c0115706da786a97cd46fe',
    messagingSenderId: '630177566427',
    projectId: 'ostadfirebase-c93c2',
    storageBucket: 'ostadfirebase-c93c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAcaDroon530EermAgNHBjCgoO-JNReA',
    appId: '1:630177566427:ios:9af2424ae90bf0b8cd46fe',
    messagingSenderId: '630177566427',
    projectId: 'ostadfirebase-c93c2',
    storageBucket: 'ostadfirebase-c93c2.firebasestorage.app',
    iosBundleId: 'wpdevusa.com.ostadFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWcbDE_5O47EXslL4dlv5hG3oQx_gJUoI',
    appId: '1:630177566427:web:78dcca8d36b7639acd46fe',
    messagingSenderId: '630177566427',
    projectId: 'ostadfirebase-c93c2',
    authDomain: 'ostadfirebase-c93c2.firebaseapp.com',
    storageBucket: 'ostadfirebase-c93c2.firebasestorage.app',
  );

}